### ISSUE TITLE
Constraint solver issue using Flutter beta channel

### ISSUE THREAD

**Issue by rcagantas** [PinkFrojd/mock_data#2]
There seems to be an issue with regards to the constraint solving. Would it be possible to bump down the lower version constraint to 2.0.0?

`The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.`
`Because ~ depends on mock_data >=1.0.1 which requires SDK version >=2.1.0 <3.0.0, version solving failed.`

**Comment by dinkopehar** [comment]
If I understand you correctly, you want version >=2.0.0 to be supported ? If so, I will  make it support that version after tests.

**Comment by rcagantas** [comment]
Well, to be honest I’m not sure where the issue is. Technically, 2.1.0-dev* should be >=2.1.0 but the constraint solver doesn’t seem to recognize it. I thought that maybe lowering the requirement (if possible) would make it work for the beta channel.

**Comment by dinkopehar** [comment]
Version **1.2.5** supports dart SDK `>=2.0.0.` and I also tested for dev version, I think all `2.1.0-dev.x.x` are also supported.

I tested with `2.1.0-dev.0.0` version, please see if this version of _mock\_data_ solved your problem 😟 .

EDIT:

Just to add, this dart sdk stable and dev versioning I don't quite understand. On [this](https://travis-ci.org/PinkFrojd/mock_data/builds/474520105) travis build, it failed at `Dart: dev/release/2.0.0-dev.0.0` although the version specified in `pubspec.yaml` is `>=2.0.0`, but passed at `Dart: dev/release/2.1.0-dev.0.0` and other stable versions; `Dart: 2.0.0` and `Dart: 2.1.0`. 😕 

If this solved your problem, I will close the issue, and also can add you to contributors list if you want :metal: .

**Comment by rcagantas** [comment]
1.2.5 solved the problem. Issue can be closed. I'm starting to think that the problem is really with the constraint solver not dealing with "-dev*" properly. Thank you for the quick turn-around!
